// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/hubsetting"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// HubSettingUpdate is the builder for updating HubSetting entities.
type HubSettingUpdate struct {
	config
	hooks    []Hook
	mutation *HubSettingMutation
}

// Where appends a list predicates to the HubSettingUpdate builder.
func (_u *HubSettingUpdate) Where(ps ...predicate.HubSetting) *HubSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValue sets the "value" field.
func (_u *HubSettingUpdate) SetValue(v string) *HubSettingUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *HubSettingUpdate) SetNillableValue(v *string) *HubSettingUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *HubSettingUpdate) SetUpdated(v time.Time) *HubSettingUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// Mutation returns the HubSettingMutation object of the builder.
func (_u *HubSettingUpdate) Mutation() *HubSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HubSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HubSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HubSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HubSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HubSettingUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := hubsetting.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

func (_u *HubSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hubsetting.Table, hubsetting.Columns, sqlgraph.NewFieldSpec(hubsetting.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(hubsetting.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(hubsetting.FieldUpdated, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hubsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HubSettingUpdateOne is the builder for updating a single HubSetting entity.
type HubSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HubSettingMutation
}

// SetValue sets the "value" field.
func (_u *HubSettingUpdateOne) SetValue(v string) *HubSettingUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *HubSettingUpdateOne) SetNillableValue(v *string) *HubSettingUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *HubSettingUpdateOne) SetUpdated(v time.Time) *HubSettingUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// Mutation returns the HubSettingMutation object of the builder.
func (_u *HubSettingUpdateOne) Mutation() *HubSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the HubSettingUpdate builder.
func (_u *HubSettingUpdateOne) Where(ps ...predicate.HubSetting) *HubSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HubSettingUpdateOne) Select(field string, fields ...string) *HubSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HubSetting entity.
func (_u *HubSettingUpdateOne) Save(ctx context.Context) (*HubSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HubSettingUpdateOne) SaveX(ctx context.Context) *HubSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HubSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HubSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HubSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := hubsetting.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

func (_u *HubSettingUpdateOne) sqlSave(ctx context.Context) (_node *HubSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(hubsetting.Table, hubsetting.Columns, sqlgraph.NewFieldSpec(hubsetting.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HubSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hubsetting.FieldID)
		for _, f := range fields {
			if !hubsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hubsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(hubsetting.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(hubsetting.FieldUpdated, field.TypeTime, value)
	}
	_node = &HubSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hubsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
