// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/hubsetting"
	"github.com/google/uuid"
)

// HubSettingCreate is the builder for creating a HubSetting entity.
type HubSettingCreate struct {
	config
	mutation *HubSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *HubSettingCreate) SetKey(v string) *HubSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *HubSettingCreate) SetValue(v string) *HubSettingCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *HubSettingCreate) SetNillableValue(v *string) *HubSettingCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *HubSettingCreate) SetCreated(v time.Time) *HubSettingCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *HubSettingCreate) SetNillableCreated(v *time.Time) *HubSettingCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *HubSettingCreate) SetUpdated(v time.Time) *HubSettingCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *HubSettingCreate) SetNillableUpdated(v *time.Time) *HubSettingCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HubSettingCreate) SetID(v uuid.UUID) *HubSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *HubSettingCreate) SetNillableID(v *uuid.UUID) *HubSettingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the HubSettingMutation object of the builder.
func (_c *HubSettingCreate) Mutation() *HubSettingMutation {
	return _c.mutation
}

// Save creates the HubSetting in the database.
func (_c *HubSettingCreate) Save(ctx context.Context) (*HubSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HubSettingCreate) SaveX(ctx context.Context) *HubSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HubSettingCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := hubsetting.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := hubsetting.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := hubsetting.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := hubsetting.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HubSettingCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "HubSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := hubsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "HubSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "HubSetting.value"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "HubSetting.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "HubSetting.updated"`)}
	}
	return nil
}

func (_c *HubSettingCreate) sqlSave(ctx context.Context) (*HubSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HubSettingCreate) createSpec() (*HubSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &HubSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hubsetting.Table, sqlgraph.NewFieldSpec(hubsetting.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(hubsetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(hubsetting.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(hubsetting.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(hubsetting.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubSetting.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubSettingUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *HubSettingCreate) OnConflict(opts ...sql.ConflictOption) *HubSettingUpsertOne {
	_c.conflict = opts
	return &HubSettingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubSettingCreate) OnConflictColumns(columns ...string) *HubSettingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubSettingUpsertOne{
		create: _c,
	}
}

type (
	// HubSettingUpsertOne is the builder for "upsert"-ing
	//  one HubSetting node.
	HubSettingUpsertOne struct {
		create *HubSettingCreate
	}

	// HubSettingUpsert is the "OnConflict" setter.
	HubSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetValue sets the "value" field.
func (u *HubSettingUpsert) SetValue(v string) *HubSettingUpsert {
	u.Set(hubsetting.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *HubSettingUpsert) UpdateValue() *HubSettingUpsert {
	u.SetExcluded(hubsetting.FieldValue)
	return u
}

// SetUpdated sets the "updated" field.
func (u *HubSettingUpsert) SetUpdated(v time.Time) *HubSettingUpsert {
	u.Set(hubsetting.FieldUpdated, v)
	return u
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *HubSettingUpsert) UpdateUpdated() *HubSettingUpsert {
	u.SetExcluded(hubsetting.FieldUpdated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.HubSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(hubsetting.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HubSettingUpsertOne) UpdateNewValues() *HubSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(hubsetting.FieldID)
		}
		if _, exists := u.create.mutation.Key(); exists {
			s.SetIgnore(hubsetting.FieldKey)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(hubsetting.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HubSettingUpsertOne) Ignore() *HubSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubSettingUpsertOne) DoNothing() *HubSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubSettingCreate.OnConflict
// documentation for more info.
func (u *HubSettingUpsertOne) Update(set func(*HubSettingUpsert)) *HubSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetValue sets the "value" field.
func (u *HubSettingUpsertOne) SetValue(v string) *HubSettingUpsertOne {
	return u.Update(func(s *HubSettingUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *HubSettingUpsertOne) UpdateValue() *HubSettingUpsertOne {
	return u.Update(func(s *HubSettingUpsert) {
		s.UpdateValue()
	})
}

// SetUpdated sets the "updated" field.
func (u *HubSettingUpsertOne) SetUpdated(v time.Time) *HubSettingUpsertOne {
	return u.Update(func(s *HubSettingUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *HubSettingUpsertOne) UpdateUpdated() *HubSettingUpsertOne {
	return u.Update(func(s *HubSettingUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *HubSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HubSettingUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: HubSettingUpsertOne.ID is not supported by MySQL driver. Use HubSettingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HubSettingUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HubSettingCreateBulk is the builder for creating many HubSetting entities in bulk.
type HubSettingCreateBulk struct {
	config
	err      error
	builders []*HubSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the HubSetting entities in the database.
func (_c *HubSettingCreateBulk) Save(ctx context.Context) ([]*HubSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HubSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HubSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HubSettingCreateBulk) SaveX(ctx context.Context) []*HubSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HubSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HubSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HubSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HubSettingUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *HubSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *HubSettingUpsertBulk {
	_c.conflict = opts
	return &HubSettingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HubSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HubSettingCreateBulk) OnConflictColumns(columns ...string) *HubSettingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HubSettingUpsertBulk{
		create: _c,
	}
}

// HubSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of HubSetting nodes.
type HubSettingUpsertBulk struct {
	create *HubSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HubSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(hubsetting.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HubSettingUpsertBulk) UpdateNewValues() *HubSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(hubsetting.FieldID)
			}
			if _, exists := b.mutation.Key(); exists {
				s.SetIgnore(hubsetting.FieldKey)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(hubsetting.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HubSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HubSettingUpsertBulk) Ignore() *HubSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HubSettingUpsertBulk) DoNothing() *HubSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HubSettingCreateBulk.OnConflict
// documentation for more info.
func (u *HubSettingUpsertBulk) Update(set func(*HubSettingUpsert)) *HubSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HubSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetValue sets the "value" field.
func (u *HubSettingUpsertBulk) SetValue(v string) *HubSettingUpsertBulk {
	return u.Update(func(s *HubSettingUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *HubSettingUpsertBulk) UpdateValue() *HubSettingUpsertBulk {
	return u.Update(func(s *HubSettingUpsert) {
		s.UpdateValue()
	})
}

// SetUpdated sets the "updated" field.
func (u *HubSettingUpsertBulk) SetUpdated(v time.Time) *HubSettingUpsertBulk {
	return u.Update(func(s *HubSettingUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *HubSettingUpsertBulk) UpdateUpdated() *HubSettingUpsertBulk {
	return u.Update(func(s *HubSettingUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *HubSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HubSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HubSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HubSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
